# Generated by Django 5.1 on 2024-08-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(auto_now_add=True)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.emprunteur')),
                ('media_consulte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.media')),
            ],
        ),
    ]
